<a href="https://colab.research.google.com/github/nsgg3532-spec/Anudeep_foundation_Davis_Python/blob/main/class%20work/numpy/ones-array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
#creation of ones array
array2=np.ones((4,3))
print(array2)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
