<a href="https://colab.research.google.com/github/nsgg3532-spec/Anudeep_foundation_Davis_Python/blob/main/class%20work/numpy/zeros-with-3-parameter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
#array creation in numpy
array2=np.zeros((3,6,2),dtype='int')
print(array2)


[[[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]]
