<a href="https://colab.research.google.com/github/nsgg3532-spec/Anudeep_foundation_Davis_Python/blob/main/class%20work/numpy/zeros.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
#array creation in numpy
array =np.zeros((5,3))
print(array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
